[phases.setup]
nixPkgs = ["python311", "pip", "git"]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu",
  "pip install --no-deps transformers pillow git+https://github.com/openai/CLIP.git",
  "pip install -r requirements.txt --no-cache-dir"
]

[start]
cmd = "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"




